### PR TITLE
Handle trailing semicolon on RTSP fmtp attribute

### LINKED ISSUE #9114: rtsp.MediaDescription.getFmtpParametersAsMap failed and crashed.
When  I to play RTSP  APP crashed

```
2021-06-25 14:46:52.448 6458-6565/com.rokid.rtspclient E/okid.rtspclien: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2021-06-25 14:46:52.451 6458-6565/com.rokid.rtspclient E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: com.rokid.rtspclient, PID: 6458
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.google.android.exoplayer2.source.rtsp.MediaDescription.getFmtpParametersAsMap(MediaDescription.java:323)
        at com.google.android.exoplayer2.source.rtsp.RtspMediaTrack.generatePayloadFormat(RtspMediaTrack.java:120)
        at com.google.android.exoplayer2.source.rtsp.RtspMediaTrack.<init>(RtspMediaTrack.java:64)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.buildTrackList(RtspClient.java:291)
        at com.google.android.exoplayer2.source.rtsp.RtspClient.access$1400(RtspClient.java:66)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.onDescribeResponseReceived(RtspClient.java:553)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:473)
        at com.google.android.exoplayer2.source.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$RtspClient$MessageListener(RtspClient.java:420)
        at com.google.android.exoplayer2.source.rtsp.-$$Lambda$RtspClient$MessageListener$dJPB0r-FyeWq7xUwLx0FyxTnUk0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

### PR DESCRIPTION
**Pull request by colinbarr**
As documented [here](https://github.com/google/ExoPlayer/issues/9114#issuecomment-890573497), an `ArrayIndexOutOfBoundsException` occurs if an `a=fmtp` line from an RTSP SDP response ends with a trailing semicolon. This change switches from using a limit of -1 on the String `split(...)` function via the Util class when parsing fmtp parameters, to using the implicit limit of 0. As a result, empty trailing strings are discarded which avoids this error condition.

Fixes #9114

### CODE REVIEW

File: library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/MediaDescription.java [hunk 1]
```diff
@@ -314,7 +314,8 @@ public int hashCode() {
 
     // Format of the parameter: RFC3640 Section 4.4.1:
     //   <parameter name>=<value>[; <parameter name>=<value>].
-    String[] parameters = Util.split(fmtpComponents[1], ";\\s?");
+    // Split with implicit limit of 0 to handle an optional trailing semicolon.
+    String[] parameters = fmtpComponents[1].split(";\\s?");
```
Comment (claincly) [inline library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/MediaDescription.java]: Maybe use an explicit limit, like

`fmtpComponents[1].split(";\\s?", /* limit= */ 0);`

**Review by claincly — CHANGES_REQUESTED** [review]

File: library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/MediaDescription.java (hunk 1 above)
Comment (colinbarr) [reply library/rtsp/src/main/java/com/google/android/exoplayer2/source/rtsp/MediaDescription.java]: No problem. It'll be [functionally equivalent](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-), but I'm happy to make the change.

**Review by claincly — APPROVED** [review]
Thanks!
